import type { Company, Tender } from "@prisma/client";
import { fetchTenderDocumentBuffer } from "@/lib/tender-documents";
import { fillTenderPdfForm } from "@/lib/pdf-form-fill";
import { buildDraftPdf, type DraftPdfSection } from "@/lib/draft-pdf";
import { BBBEE_LEVELS } from "@/lib/constants";

export interface DraftDocument {
  label: string;
  buffer: Buffer;
  kind: "official_form_filled" | "generated_equivalent";
  filename: string;
}

/**
 * For each of the tender's linked PDFs, tries to fill the real supplied
 * form's AcroForm fields (objective data only — see pdf-form-fill.ts).
 * If NONE of the tender's documents turn out to be fillable (flat/scanned
 * forms, or no form at all), falls back to generating our own equivalent
 * compliance document instead — per Phase 4's spec, official forms are
 * always preferred when they're actually usable.
 */
export async function generateComplianceDocuments(
  company: Company,
  tender: Tender
): Promise<DraftDocument[]> {
  const documents: DraftDocument[] = [];

  for (const [i, url] of tender.documentUrls.slice(0, 5).entries()) {
    if (!url.toLowerCase().includes(".pdf") && !url.toLowerCase().endsWith("pdf")) continue;
    const bytes = await fetchTenderDocumentBuffer(url);
    if (!bytes) continue;

    const result = await fillTenderPdfForm(bytes, company);
    if (result) {
      documents.push({
        label: `Official form ${i + 1} (pre-filled draft)`,
        buffer: result.buffer,
        kind: "official_form_filled",
        filename: `official-form-${i + 1}-draft.pdf`,
      });
    }
  }

  if (documents.length > 0) return documents;

  // Fallback: none of the tender's own documents had a fillable form —
  // generate our own equivalent instead, clearly labeled as such.
  const equivalent = await buildEquivalentComplianceDocument(company, tender);
  return [{ label: "Company compliance summary (Tenderiza-generated equivalent)", buffer: equivalent, kind: "generated_equivalent", filename: "compliance-summary-draft.pdf" }];
}

async function buildEquivalentComplianceDocument(company: Company, tender: Tender): Promise<Buffer> {
  const bbbeeLabel = company.bbbeeLevel
    ? BBBEE_LEVELS.find((l) => l.value === company.bbbeeLevel)?.label ?? company.bbbeeLevel
    : "Not set in profile";

  const sections: DraftPdfSection[] = [
    {
      heading: "Note",
      body:
        "This document was generated by Tenderiza because none of this tender's own supplied forms " +
        "could be automatically filled (they may be flat/scanned images, or no fillable form was " +
        "supplied at all). It is NOT the official bid document — use it as a reference for your own " +
        "company information while completing the tender's actual required forms.",
    },
    {
      heading: "Company details",
      body: [
        `Company name: ${company.tradingName || company.companyName || "—"}`,
        `Registration number: ${company.registrationNumber || "—"}`,
        `VAT number: ${company.vatNumber || "—"}`,
        `Physical address: ${[company.addressLine1, company.addressLine2, company.city, company.postalCode].filter(Boolean).join(", ") || "—"}`,
        `Contact person: ${company.contactPersonName || "—"}`,
        `Contact email: ${company.contactEmail || "—"}`,
        `Contact phone: ${company.contactPhone || "—"}`,
      ].join("\n"),
    },
    {
      heading: "Compliance status",
      body: [
        `B-BBEE level: ${bbbeeLabel}`,
        `CIDB grading: ${company.cidbGrade ? `Grade ${company.cidbGrade}${company.cidbClassOfWork ? ` (${company.cidbClassOfWork})` : ""}` : "Not set in profile"}`,
        `CSD registration number: ${company.csdRegistrationNumber || "—"}`,
        `Tax compliance status PIN: ${company.taxComplianceStatusPin || "—"}`,
      ].join("\n"),
    },
    {
      heading: "Declarations and sign-off",
      body:
        "[TO BE COMPLETED BY BIDDER — REQUIRES SIGN-OFF]\n\n" +
        "This tender's actual declarations (conflicts of interest, past supply chain conduct, " +
        "authenticity of B-BBEE status, and any other sworn statements) must be completed and signed " +
        "on the tender's own official forms — they are not reproduced here, since they require your " +
        "direct attestation and cannot be auto-filled.",
    },
  ];

  return buildDraftPdf(`Compliance Summary — ${tender.title || tender.ocid}`, sections);
}
